---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ducktales-dev
  namespace: ducktales-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ducktales-dev
  template:
    metadata:
      labels:
        app: ducktales-dev
    spec:
      containers:
        - name: ducktales-dev
          image: localhost:5000/ducktales:v1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.25"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "50Mi"
          env:
            - name: DUCK
              valueFrom:
                secretKeyRef:
                  name: duck
                  key: user
