---
  kind: Service
  apiVersion: v1
  metadata:
    name: ducktales-dev
    namespace: ducktales-dev
  spec:
    selector:
      app: ducktales-dev
    ports:
      - name: http
        port: 8100
        protocol: TCP
        targetPort: 8080
    type: NodePort
  