---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: ducktales-test
---
  apiVersion: v1
  kind: Secret
  metadata:
    name: duck
    namespace: ducktales-test
  type: Opaque
  data:
    user: SHVleQ==
--- 
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ducktales-test
    namespace: ducktales-test
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: ducktales-test
    template:
      metadata:
        labels:
          app: ducktales-test
      spec:
        containers:
          - name: ducktales-test
            image: localhost:5000/ducktales:v1
            imagePullPolicy: Always
            resources:
              limits:
                cpu: "0.25"
                memory: "512Mi"
              requests:
                cpu: "250m"
                memory: "50Mi"
            env:
              - name: DUCK
                valueFrom:
                  secretKeyRef:
                    name: duck
                    key: user
---
  kind: Service
  apiVersion: v1
  metadata:
    name: ducktales-test
    namespace: ducktales-test
  spec:
    selector:
      app: ducktales-test
    ports:
      - name: http
        port: 8101
        protocol: TCP
        targetPort: 8080
    type: NodePort
      