parameters:
  - name: "ArtifactName"
    type: string
  - name: "AzureCredentials"
    type: string
  - name: "ACRURL"
    type: string
  - name: "Name"
    type: string
jobs:
  - job: ${{ parameters.Name }}
    displayName: "docker build and push:  ${{ parameters.Name }}"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        displayName: "Download docker artifact"
        inputs:
          buildType: "current"
          artifactName: "${{ parameters.ArtifactName }}"
      - task: AzureCLI@2
        displayName: 'Azure CLI'
        inputs:
          azureSubscription: "${{ parameters.AzureCredentials }}"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login --name $(ACRURL)
            cd $(Pipeline.Workspace)/${{parameters.Name}}
            docker build -t $(ACRURL)/$(image.name):$(build.buildnumber) -t $(ACRURL)/$(image.name):latest .
            docker push $(ACRURL)/$(image.name):$(build.buildnumber)
      - script: |
          echo "##vso[task.setvariable variable=image;isOutput=true]${{parameters.ACRURL}}:$(build.buildnumber)"
        name: outputs
        displayName: "create stage outputs"
