parameters:
  - name: "ArtifactName"
    type: string
  - name: "SecureFileName"
    type: string
  - name: "GcpRegion"
    type: string
  - name: "GcpProjectId"
    type: string
  - name: "GcpSdkVersion"
    type: string
  - name: "GCRUrl"
    type: string
  - name: "Name"
    type: string
jobs:
  - job: ${{ parameters.Name }}
    displayName: "docker build and push:  ${{ parameters.Name }}"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        displayName: "Download docker artifact"
        inputs:
          buildType: "current"
          artifactName: "${{ parameters.ArtifactName }}"
      - task: DownloadSecureFile@1
        name: authkey
        displayName: 'Download GCP Secure File'
        inputs:
          secureFile: ${{parameters.SecureFileName}}
      - task: nexso.azure-devops-google-cloud-tools.GoogleCloudSdkTool.GoogleCloudSdkTool@1
        displayName: 'Install gcloud sdk'
        inputs:
          versionSpec: "${{ parameters.GcpSdkVersion}}"
      - script: |
          cat  $(authkey.secureFilePath) | docker login -u _json_key --password-stdin https://$(GCRUrl)
        displayName: "GCP GCR Authenticate"
      - task: Docker@2
        displayName: "build docker image"
        inputs:
          repository: ${{parameters.GCRUrl}}
          command: "buildAndPush"
          Dockerfile: "$(Pipeline.Workspace)/${{parameters.Name}}/Dockerfile"
          tags: |
            $(build.buildnumber)
            latest
      - script: |
          echo "##vso[task.setvariable variable=image;isOutput=true]${{parameters.GCRUrl}}:$(build.buildnumber)"
        name: outputs
        displayName: "create stage outputs"
