- name: update mysql root password for all root accounts
  mysql_user:
    name: "{{ user }}"
    host: "{{ item }}"
    password: "{{ password }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: create a new database
  mysql_db:
    name: "{{ edgar_database }}"
    state: present
    login_user: "{{ user }}"
    login_password: "{{ password }}"
