- name: Ensure runtime group exists
  ansible.builtin.group:
    name: "{{ user }}"
    state: present

- name: "Create runtime user account and add user to group"
  user:
    name: "{{ user }}"
    groups: "{{ user }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '{{ user_pub_key }}') }}"
